export async function getData() {
  // Fetch data from your API here.
  return [
    {
      id: "728edm52f",
      date: "Dec 8, 2025",
      description: "uber",
      category: "Transportation",
      paymentMethod: "Bank Transfer",
      amount: 200,
      type: "Expense",
      status: "Completed",
    },
    {
      id: "72v8ed52f",
      date: "Jul 7, 2025",
      description: "music subscription",
      category: "Entertainment",
      paymentMethod: "Auto-pay",
      amount: 120,
      type: "Expense",
      status: "Completed",
    },
    {
      id: "728edb52f",
      date: "Jun 6, 2025",
      description: "netflix",
      category: "Entertainment",
      paymentMethod: "Card",
      amount: 300,
      type: "Expense",
      status: "Completed",
    },
    {
      id: "728ed5k2f",
      date: "May 5, 2025",
      description: "restaurant",
      category: "Food & Dining",
      paymentMethod: "Card",
      amount: 450,
      type: "Expense",
      status: "Completed",
    },
    {
      id: "28ed52f",
      date: "Apr 4, 2025",
      description: "grocery shopping",
      category: "Food & Dining",
      paymentMethod: "Card",
      amount: 1000,
      type: "Expense",
      status: "Completed",
    },
    {
      id: "78ed52f",
      date: "Mar 3, 2025",
      description: "gym membership",
      category: "Health",
      paymentMethod: "Card",
      amount: 900,
      type: "Expense",
      status: "Completed",
    },
    {
      id: "728d52f",
      date: "Feb 2, 2025",
      description: "gas station",
      category: "Transportation",
      paymentMethod: "Card",
      amount: 419,
      type: "Expense",
      status: "Completed",
    },
    {
      id: "72ed52f",
      date: "Jan 1, 2025",
      description: "electricity bill",
      category: "Utilities",
      paymentMethod: "Bank Transfer",
      amount: 673,
      type: "Expense",
      status: "Completed",
    },
    {
      id: "728e52f",
      date: "Nov 30, 2025",
      description: "taxi",
      category: "Transportation",
      paymentMethod: "Cash",
      amount: 580,
      type: "Expense",
      status: "Completed",
    },
    {
      id: "728ed2f",
      date: "Nov 29, 2025",
      description: "mega chicken",
      category: "Food & Dining",
      paymentMethod: "Card",
      amount: 77,
      type: "Expense",
      status: "Completed",
    },
    {
      id: "728ed5f",
      date: "Nov 28, 2025",
      description: "rent",
      category: "Housing",
      paymentMethod: "Bank Transfer",
      amount: 820,
      type: "Expense",
      status: "Pending",
    },
    {
      id: "728ed52",
      date: "Nov 30, 2025",
      description: "salary",
      category: "Income",
      paymentMethod: "Bank Transfer",
      amount: 5000,
      type: "Income",
      status: "Completed",
    },
  ];
}

export const categoryOptions = [
  { label: "Entertainment", value: "Entertainment" },
  { label: "Food & Dining", value: "Food & Dining" },
  { label: "Health", value: "Health" },
  { label: "Housing", value: "Housing" },
  { label: "Income", value: "Income" },
  { label: "Shopping", value: "Shopping" },
  { label: "Transportation", value: "Transportation" },
  { label: "Utilities", value: "Utilities" },
];
